### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by streetlamplee** [upstage-git-project-team4/final-project#1]
## Description
필수 : fizzbuzz 구현

## Tasks
- [ ] do fizz
- [ ] do buzz
- [ ] do fizzbuzz

**Comment by suinY00N** [comment]
1. 100 Prisoners Problem(https://en.wikipedia.org/wiki/ 100_prisoners_problem, n회 시행시 성공 확률 출력)
2. Pig Dice Game(https://www.mathsweek.ie/2021/games/pig.html, only CLI)
3. Monty Hall Problem Simulation(https://en.wikipedia.org/wiki/ Monty_Hall_problem, n회 시행시 시뮬레이션 결과 출력)
